// <auto-generated />
using System;
using InfrastructureEfPersistance.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InfrastructureEfPersistance.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260904113654_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DomainModel.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("AssignedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("LaboratoryDepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("_identityUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UserId");

                    b.HasKey("EmployeeId");

                    b.HasIndex("AssignedByEmployeeId");

                    b.HasIndex("LaboratoryDepartmentId");

                    b.HasIndex("_identityUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Employees_UserId");

                    b.ToTable("Employees", "dbo");
                });

            modelBuilder.Entity("DomainModel.Models.LaboratoryDepartment", b =>
                {
                    b.Property<int>("LaboratoryDepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LaboratoryDepartmentId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LaboratoryDepartmentId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("LaboratoryDepartments", "dbo");
                });

            modelBuilder.Entity("DomainModel.Models.LaboratoryTest", b =>
                {
                    b.Property<int>("LaboratoryTestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LaboratoryTestId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("LaboratoryDepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("SampleTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LaboratoryTestId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("SampleTypeId");

                    b.HasIndex("LaboratoryDepartmentId", "IsActive");

                    b.ToTable("LaboratoryTests", "dbo");
                });

            modelBuilder.Entity("DomainModel.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Mobile")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NationalCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("RegisteredByEmployeeId")
                        .HasColumnType("int");

                    b.HasKey("PatientId");

                    b.HasIndex("Mobile")
                        .HasFilter("[Mobile] IS NOT NULL");

                    b.HasIndex("NationalCode")
                        .IsUnique()
                        .HasFilter("[NationalCode] IS NOT NULL");

                    b.HasIndex("RegisteredByEmployeeId");

                    b.ToTable("Patients", "dbo");
                });

            modelBuilder.Entity("DomainModel.Models.ResultReview", b =>
                {
                    b.Property<int>("ResultReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultReviewId"));

                    b.Property<string>("ReviewDescription")
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("ReviewedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("ReviewedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("TestResultId")
                        .HasColumnType("int");

                    b.HasKey("ResultReviewId");

                    b.HasIndex("ReviewedByEmployeeId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TestResultId", "ReviewedAtUtc");

                    b.ToTable("ResultReviews", "dbo");
                });

            modelBuilder.Entity("DomainModel.Models.Sample", b =>
                {
                    b.Property<int>("SampleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SampleId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CollectedAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("CollectedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("LaboratoryDepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SampleTypeId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("TestRequestId")
                        .HasColumnType("int");

                    b.HasKey("SampleId");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.HasIndex("CollectedByEmployeeId");

                    b.HasIndex("SampleTypeId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TestRequestId");

                    b.HasIndex("LaboratoryDepartmentId", "StatusId", "CollectedAtUtc");

                    b.ToTable("Samples", "dbo");
                });

            modelBuilder.Entity("DomainModel.Models.SampleType", b =>
                {
                    b.Property<int>("SampleTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SampleTypeId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SampleTypeId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("SampleTypes", "dbo");
                });

            modelBuilder.Entity("DomainModel.Models.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<short>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsFinal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StatusId");

                    b.HasIndex("EntityName", "Code")
                        .IsUnique();

                    b.HasIndex("EntityName", "DisplayOrder")
                        .IsUnique();

                    b.ToTable("Statuses", "dbo");
                });

            modelBuilder.Entity("DomainModel.Models.TestRequest", b =>
                {
                    b.Property<int>("TestRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestRequestId"));

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegisteredAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("RegisteredByEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("TestRequestId");

                    b.HasIndex("RegisteredByEmployeeId");

                    b.HasIndex("RequestNumber")
                        .IsUnique();

                    b.HasIndex("PatientId", "RegisteredAtUtc");

                    b.HasIndex("StatusId", "RegisteredAtUtc");

                    b.ToTable("TestRequests", "dbo");
                });

            modelBuilder.Entity("DomainModel.Models.TestRequestItem", b =>
                {
                    b.Property<int>("TestRequestItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestRequestItemId"));

                    b.Property<int>("LaboratoryTestId")
                        .HasColumnType("int");

                    b.Property<int?>("SampleId")
                        .HasColumnType("int");

                    b.Property<string>("TestNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TestRequestId")
                        .HasColumnType("int");

                    b.Property<string>("UnitSnapshot")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TestRequestItemId");

                    b.HasIndex("LaboratoryTestId");

                    b.HasIndex("SampleId");

                    b.HasIndex("TestRequestId", "LaboratoryTestId")
                        .IsUnique();

                    b.ToTable("TestRequestItems", "dbo");
                });

            modelBuilder.Entity("DomainModel.Models.TestResult", b =>
                {
                    b.Property<int>("TestResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestResultId"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("EnteredAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("EnteredByEmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("ResultValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("TestRequestItemId")
                        .HasColumnType("int");

                    b.HasKey("TestResultId");

                    b.HasIndex("EnteredByEmployeeId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TestRequestItemId")
                        .IsUnique();

                    b.ToTable("TestResults", "dbo");
                });

            modelBuilder.Entity("InfrastructureEfPersistance.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("InfrastructureEfPersistance.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)")
                        .HasDefaultValue("");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DomainModel.Models.Employee", b =>
                {
                    b.HasOne("DomainModel.Models.Employee", "AssignedByEmployee")
                        .WithMany("AssignedEmployees")
                        .HasForeignKey("AssignedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DomainModel.Models.LaboratoryDepartment", "LaboratoryDepartment")
                        .WithMany("Employees")
                        .HasForeignKey("LaboratoryDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InfrastructureEfPersistance.ApplicationUser", null)
                        .WithOne("Employee")
                        .HasForeignKey("DomainModel.Models.Employee", "_identityUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedByEmployee");

                    b.Navigation("LaboratoryDepartment");
                });

            modelBuilder.Entity("DomainModel.Models.LaboratoryTest", b =>
                {
                    b.HasOne("DomainModel.Models.LaboratoryDepartment", "LaboratoryDepartment")
                        .WithMany("LaboratoryTests")
                        .HasForeignKey("LaboratoryDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DomainModel.Models.SampleType", "SampleType")
                        .WithMany("LaboratoryTests")
                        .HasForeignKey("SampleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LaboratoryDepartment");

                    b.Navigation("SampleType");
                });

            modelBuilder.Entity("DomainModel.Models.Patient", b =>
                {
                    b.HasOne("DomainModel.Models.Employee", "RegisteredByEmployee")
                        .WithMany("Patients")
                        .HasForeignKey("RegisteredByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RegisteredByEmployee");
                });

            modelBuilder.Entity("DomainModel.Models.ResultReview", b =>
                {
                    b.HasOne("DomainModel.Models.Employee", "ReviewedByEmployee")
                        .WithMany("ResultReviews")
                        .HasForeignKey("ReviewedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DomainModel.Models.Status", "Status")
                        .WithMany("ResultReviews")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DomainModel.Models.TestResult", "TestResult")
                        .WithMany("ResultReviews")
                        .HasForeignKey("TestResultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReviewedByEmployee");

                    b.Navigation("Status");

                    b.Navigation("TestResult");
                });

            modelBuilder.Entity("DomainModel.Models.Sample", b =>
                {
                    b.HasOne("DomainModel.Models.Employee", "CollectedByEmployee")
                        .WithMany("Samples")
                        .HasForeignKey("CollectedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DomainModel.Models.LaboratoryDepartment", "LaboratoryDepartment")
                        .WithMany("Samples")
                        .HasForeignKey("LaboratoryDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DomainModel.Models.SampleType", "SampleType")
                        .WithMany("Samples")
                        .HasForeignKey("SampleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DomainModel.Models.Status", "Status")
                        .WithMany("Samples")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DomainModel.Models.TestRequest", "TestRequest")
                        .WithMany("Samples")
                        .HasForeignKey("TestRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CollectedByEmployee");

                    b.Navigation("LaboratoryDepartment");

                    b.Navigation("SampleType");

                    b.Navigation("Status");

                    b.Navigation("TestRequest");
                });

            modelBuilder.Entity("DomainModel.Models.TestRequest", b =>
                {
                    b.HasOne("DomainModel.Models.Patient", "Patient")
                        .WithMany("TestRequests")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DomainModel.Models.Employee", "RegisteredByEmployee")
                        .WithMany("TestRequests")
                        .HasForeignKey("RegisteredByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DomainModel.Models.Status", "Status")
                        .WithMany("TestRequests")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("RegisteredByEmployee");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("DomainModel.Models.TestRequestItem", b =>
                {
                    b.HasOne("DomainModel.Models.LaboratoryTest", "LaboratoryTest")
                        .WithMany("TestRequestItems")
                        .HasForeignKey("LaboratoryTestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DomainModel.Models.Sample", "Sample")
                        .WithMany("TestRequestItems")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DomainModel.Models.TestRequest", "TestRequest")
                        .WithMany("Items")
                        .HasForeignKey("TestRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LaboratoryTest");

                    b.Navigation("Sample");

                    b.Navigation("TestRequest");
                });

            modelBuilder.Entity("DomainModel.Models.TestResult", b =>
                {
                    b.HasOne("DomainModel.Models.Employee", "EnteredByEmployee")
                        .WithMany("TestResults")
                        .HasForeignKey("EnteredByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DomainModel.Models.Status", "Status")
                        .WithMany("TestResults")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DomainModel.Models.TestRequestItem", "TestRequestItem")
                        .WithOne("TestResult")
                        .HasForeignKey("DomainModel.Models.TestResult", "TestRequestItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EnteredByEmployee");

                    b.Navigation("Status");

                    b.Navigation("TestRequestItem");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("InfrastructureEfPersistance.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("InfrastructureEfPersistance.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("InfrastructureEfPersistance.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("InfrastructureEfPersistance.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InfrastructureEfPersistance.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("InfrastructureEfPersistance.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DomainModel.Models.Employee", b =>
                {
                    b.Navigation("AssignedEmployees");

                    b.Navigation("Patients");

                    b.Navigation("ResultReviews");

                    b.Navigation("Samples");

                    b.Navigation("TestRequests");

                    b.Navigation("TestResults");
                });

            modelBuilder.Entity("DomainModel.Models.LaboratoryDepartment", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("LaboratoryTests");

                    b.Navigation("Samples");
                });

            modelBuilder.Entity("DomainModel.Models.LaboratoryTest", b =>
                {
                    b.Navigation("TestRequestItems");
                });

            modelBuilder.Entity("DomainModel.Models.Patient", b =>
                {
                    b.Navigation("TestRequests");
                });

            modelBuilder.Entity("DomainModel.Models.Sample", b =>
                {
                    b.Navigation("TestRequestItems");
                });

            modelBuilder.Entity("DomainModel.Models.SampleType", b =>
                {
                    b.Navigation("LaboratoryTests");

                    b.Navigation("Samples");
                });

            modelBuilder.Entity("DomainModel.Models.Status", b =>
                {
                    b.Navigation("ResultReviews");

                    b.Navigation("Samples");

                    b.Navigation("TestRequests");

                    b.Navigation("TestResults");
                });

            modelBuilder.Entity("DomainModel.Models.TestRequest", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Samples");
                });

            modelBuilder.Entity("DomainModel.Models.TestRequestItem", b =>
                {
                    b.Navigation("TestResult");
                });

            modelBuilder.Entity("DomainModel.Models.TestResult", b =>
                {
                    b.Navigation("ResultReviews");
                });

            modelBuilder.Entity("InfrastructureEfPersistance.ApplicationUser", b =>
                {
                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
